### ISSUE TITLE
r'**' shown as error

### ISSUE THREAD

**Issue by MaxGyver83** [Galicarnax/vim-regex-syntax#1]
Hello @Galicarnax,

thank you for this awesome plugin.

I think I found a bug. In this line, the second `*` (in the substitute) looks like a syntax error:

![image](https://user-images.githubusercontent.com/13970628/186982362-0b137d31-dfd3-4ebb-bbbb-f42ce2a9668a.png)

`**` is meant as two literal asterisks. The output `string` is `**test**`.

**Comment by Galicarnax** [comment]
Hi, I am not sure this is a bug. In a a normal regex, that indeed would be an error. But the second argument to `re.sub` is actually not an honest regex pattern, but a replacement string in which only few regex elements are recognized (such as backreferences). My suggestion would be to use upper-case `R` in this case (`R'**\1**'`), which disables plugin's highlighting.

**Comment by MaxGyver83** [comment]
I see. Thank you for the explanation!
